


name: CICD

on:
    push:
      branches: [main]

jobs:
    build:

      runs-on: ubuntu-latest

      steps: 

        - run: echo "Start Build Process"

        - name: Checkout
          uses: actions/checkout@v4.2.2


        - name: check code and install dependencies 
          run: |
                ls 
                node -v
                npm ci

        - name: build
          run: |
                npm run build
                ls

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.4.3
          with:
            name: dist-files
            path: ./dist
            

    deploy:
        
      runs-on: ubuntu-latest
      needs: build
      steps:
      
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.8
          with:
            name: dist-files
            path: ./dist
    
        - run: ls






    
