


name: CICD

on:
    push:
      branches: [main]

jobs:
    build:

      runs-on: ubuntu-latest

      steps: 

        - run: echo "Start Build Process"

        - name: Checkout
          uses: actions/checkout@v4.2.2


        - name: check code and install dependencies 
          run: |
                ls 
                node -v
                npm ci

        - name: build
          run: |
                npm run build
                ls

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.4.3
          with:
            name: dist-files
            path: ./dist
            

    deploy:
        
      runs-on: ubuntu-latest
      needs: build
      steps:
      
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.8
          with:
            name: dist-files
            path: ./dist
    
        - run: ls


        - name: install-aws-cli-action
          uses: unfor19/install-aws-cli-action@v1
        - run: echo "$super_secret" > ~/.aws/credentials
          env: 
            super_secret: ${{ secrets.AWS_CONFIG }}
        - run: aws configure list-profiles
        - run: aws s3 ls --region eu-central-1 --profile techstarter
        - run: aws s3 sync --region eu-central-1 ./dist s3://mywebsitezicke/ --profile techstarter         






    
